run:
  timeout: 3m
  tests: true

linters:
  enable:
    - copyloopvar
    - dupl
    - errcheck
    #- gocognit
    - gocritic
    - gocyclo
    - godot # doc comment formatting
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - predeclared
    - revive
    - staticcheck
    - unparam
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/staranto/tflint-ruleset-elements-of-style
  revive:
    rules:
      - name: dot-imports
      - name: exported
      - name: var-naming
      - name: receiver-naming

  godot:
    scope: all
    period: false

issues:
  exclude-files:
    - .*_test\.go$
    - .*testdata/.*
  exclude-rules:
